[package]
name = "valet_core"
type = "lib"
version = "0.1.0"
std = "c++20"
includes = ["../../third_party", "./include", "./src"]
public_includes = ["./include/"]
compile_options = ["-Wno-unknown-pragmas"]