name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    name: "Build valet"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure CMake
        run: cmake -S . -B ./cmake_build/

      - name: Build
        run: cmake --build ./cmake_build/

      - name: Self-hosted Build
        run: ./cmake_build/valet -v build

      - name: Build Test Projects
        run: |
          ./cmake_build/valet -v build -s test/test_projects/deep_deps/
          ./cmake_build/valet -v build -s test/test_projects/primes/
          ./cmake_build/valet -v build -s test/test_projects/primes_remote_dep/
          ./cmake_build/valet -v build -s test/test_projects/eratosthenes_dylib/
          ./cmake_build/valet -v build -s test/test_projects/header_only_deps/check_even
      
      - name: Run Unit Tests
        run: |
          ./cmake_build/valet -v run -s test/valet_tests/