name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    name: "Build valet"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}

      - name: Configure CMake
        run: cmake -S . -B ./cmake_build/

      - name: Build
        run: cmake --build ./cmake_build/

      - name: Bootstrap
        run: ./cmake_build/valet -v

      - name: Build Test Projects
        run: |
          ./cmake_build/valet -s test/test_projects/deep_deps/ -v
          ./cmake_build/valet -s test/test_projects/primes/ -v
      
      - name: Run Unit Tests
        run: |
          ./cmake_build/valet -s test/unit -v -r valet_tests