name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CC: "clang"
  CXX: "clang++"

jobs:
  build:
    runs-on: self-hosted

    name: "Build autob"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}

      - name: Configure CMake
        run: cmake -S . -B ./cmake_build/

      - name: Build
        run: cmake --build ./cmake_build/

      - name: Bootstrap
        run: ./cmake_build/autob -s . -v